steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/crackerfrontend/frontend-image',
        '.'
      ]

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/crackerfrontend/frontend-image'
      ]

  #Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'frontend-service',         # <-- Change this name if you want
        '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/crackerfrontend/frontend-image',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated'                    # <-- Optional: make public
      ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/crackerfrontend/frontend-image'

options:
  logging: CLOUD_LOGGING_ONLY
