# cloudbuild.yaml in your repository root

steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker' # Use the Docker builder
  args:
    - 'build'
    - '-t' # Tag the image
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-service:$COMMIT_SHA' # Image name with a unique tag (commit SHA)
    - '.' # Build context is the current directory

# Step 2: Push the Docker image to Artifact Registry
# (Note: if you list the image in the 'images' section below, Cloud Build handles this automatically after successful build)
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-service:$COMMIT_SHA'

# Step 3: Deploy the new image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk' # Use the Google Cloud SDK builder
  entrypoint: 'gcloud' # Specify 'gcloud' as the command to run
  args:
    - 'run'
    - 'deploy'
    - 'my-cloud-run-service-name' # The name of your Cloud Run service
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-service:$COMMIT_SHA' # The image to deploy
    - '--region'
    - 'us-central1' # The region where your Cloud Run service
