steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image', '.' ]
  
- name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/quickstart-image']
 
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      'gcloud', 'run', 'deploy', 'quickstart-image',
      '--image', 'gcr.io/$PROJECT_ID/quickstart-image',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]

    images:
  - 'gcr.io/$PROJECT_ID/quickstart-image'

options:
  logging: CLOUD_LOGGING_ONLY
